Update to Go 1.21 and Node 20 (#189)

diff --git a/dev-scripts/run-go-tests b/dev-scripts/run-go-tests
--- a/dev-scripts/run-go-tests
+++ b/dev-scripts/run-go-tests
@@ -1,13 +1,24 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# Exit build script on first failure.
+# Runs all unit tests and performs static code analysis.
+#
+# Options:
+#
+#  --full   Include slower, more exhaustive tests and capture test coverage
+#           results (outputs to .coverage.html).
+
+# Exit on first failure.
 set -e
 
-# Echo commands to stdout.
+# Echo commands before executing them, by default to stderr.
 set -x
 
+# Fail when piped commands fail.
+set -o pipefail
+
 full_test=""
-go_test_flags=()
+# Without netgo and osusergo, compilation fails under Nix.
+go_test_flags=("-tags=netgo,osusergo")
 readonly COVERAGE_FILE_RAW=".coverage.out"
 readonly COVERAGE_FILE_HTML=".coverage.html"
 if [[ "$1" = "--full" ]]; then
@@ -35,17 +46,21 @@ go vet ./...
 # Install staticcheck if it's not present.
 STATICCHECK_PATH="$(go env GOPATH)/bin/staticcheck"
 readonly STATICCHECK_PATH
-readonly STATICCHECK_VERSION="v0.3.3"
+readonly STATICCHECK_VERSION="v0.4.6"
 if [[ ! -f "${STATICCHECK_PATH}" ]]; then
-    go install "honnef.co/go/tools/cmd/staticcheck@${STATICCHECK_VERSION}"
+    go install \
+      -ldflags=-linkmode=external \
+      "honnef.co/go/tools/cmd/staticcheck@${STATICCHECK_VERSION}"
 fi
 "${STATICCHECK_PATH}" ./...
 
 # Install errcheck if it's not present.
 ERRCHECK_PATH="$(go env GOPATH)/bin/errcheck"
 readonly ERRCHECK_PATH
-readonly ERRCHECK_VERSION="v1.6.1"
+readonly ERRCHECK_VERSION="v1.6.2"
 if [[ ! -f "${ERRCHECK_PATH}" ]]; then
-    go install "github.com/kisielk/errcheck@${ERRCHECK_VERSION}"
+    go install \
+      -ldflags=-linkmode=external \
+      "github.com/kisielk/errcheck@${ERRCHECK_VERSION}"
 fi
 "${ERRCHECK_PATH}" -ignoretests ./...
